05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WapFront.Util;

namespace WapFront.Controllers
{
    public class GameController : Controller
    {
        //
        // GET: /Game/

        public ActionResult Index(int? id)
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.Title = "Trò chơi";
            ViewBag.CSSClass = "game";
            if (id.HasValue)
            {
                return View("Detail/Index" + client.client);
            }
            else
            {
                return View("Index" + client.client);
            }
            
        }

        public ActionResult Topic(int Id = 1)
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.Title = "Trò chơi";
            ViewBag.CSSClass = "game";
            return View("Index" + client.client);
        }

    }
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WapFront.Models;
using System.IO;
using System.Configuration;
using WapFront.Util;

namespace WapFront.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.CSSClass = "home";
            return View("Index" + client.client);    
            
        }

        public ActionResult Category()
        {
            string agent = Request.UserAgent.ToLower();
            string smartPhonePattern = "ipad|ipod|android|opera mini|palm os|palm|hiptop|avantgo|plucker|xiino|blazer|elaine|mini 9.5|vx1000|lge |m800|e860|u940|ux840|compal|wireless| mobi|ahong|lg380|lgku|lgu900|lg210|lg47|lg920|lg840|lg370|sam-r|mg50|s55|g83|t66|vx400|mk99|d615|d763|el370|sl900|mp500|samu3|samu4|vx10|xda_|samu5|samu6|samu7|samu9|a615|b832|m881|s920|n210|s700|c-810|_h797|mob-x|sk16d|848b|mowser|s580|r800|471x|v120|rim8|c500foma:|160x|x160|480x|x640|t503|w839|i250|sprint|w398samr810|m5252|c7100|mt126|x225|s5330|s820|htil-g1|fly v71|s302|-x113|novarra|k610i|-three|8325rc|8352rc|sanyo|vx54|c888|nx250|n120|mtk |c5588|s710|t880|c5005|i;458x|p404i|s210|c5100|teleca|s940|c500|s590|foma|samsu|vx8|vx9|a1000|_mms|myx|a700|gu1100|bc831|e300|ems100|me701|me702m-three|sd588|s800|8325rc|ac831|mw200|brew |d88|htc/|htc_touch|355x|m50|km100|d736|p-9521|telco|sl74|ktouch|m4u/|me702|8325rc|kddi|phone|lg |sonyericsson|samsung|240x|x320|vx10|nokia|sony cmd|motorola|up.browser|up.link|mmp|symbian|smartphone|midp|wap|vodafone|o2|pocket|kindle|mobile|psp|treo|iris|3g_t|windows ce|opera mobi|windows ce; smartphone;|windows ce; iemobile";
            string WAPPattern = "j2me|nokia109";

            ViewBag.Agent = agent;

            if (System.Text.RegularExpressions.Regex.IsMatch(agent, WAPPattern))
            {
                ViewBag.CSS = "~/Content/WAP.css";
                return View("Category-WAP");
            }
            else if (System.Text.RegularExpressions.Regex.IsMatch(agent, smartPhonePattern))
            {
                ViewBag.CSS = "~/Content/SmartPhone.css";
                return View("Category-SmartPhone");
            }
            else
            {
                ViewBag.CSS = "~/Content/Desktop.css";
                return View();
            }
        }

        public ActionResult Detail()
        {
            string agent = Request.UserAgent.ToLower();
            string smartPhonePattern = "ipad|ipod|android|opera mini|palm os|palm|hiptop|avantgo|plucker|xiino|blazer|elaine|mini 9.5|vx1000|lge |m800|e860|u940|ux840|compal|wireless| mobi|ahong|lg380|lgku|lgu900|lg210|lg47|lg920|lg840|lg370|sam-r|mg50|s55|g83|t66|vx400|mk99|d615|d763|el370|sl900|mp500|samu3|samu4|vx10|xda_|samu5|samu6|samu7|samu9|a615|b832|m881|s920|n210|s700|c-810|_h797|mob-x|sk16d|848b|mowser|s580|r800|471x|v120|rim8|c500foma:|160x|x160|480x|x640|t503|w839|i250|sprint|w398samr810|m5252|c7100|mt126|x225|s5330|s820|htil-g1|fly v71|s302|-x113|novarra|k610i|-three|8325rc|8352rc|sanyo|vx54|c888|nx250|n120|mtk |c5588|s710|t880|c5005|i;458x|p404i|s210|c5100|teleca|s940|c500|s590|foma|samsu|vx8|vx9|a1000|_mms|myx|a700|gu1100|bc831|e300|ems100|me701|me702m-three|sd588|s800|8325rc|ac831|mw200|brew |d88|htc/|htc_touch|355x|m50|km100|d736|p-9521|telco|sl74|ktouch|m4u/|me702|8325rc|kddi|phone|lg |sonyericsson|samsung|240x|x320|vx10|nokia|sony cmd|motorola|up.browser|up.link|mmp|symbian|smartphone|midp|wap|vodafone|o2|pocket|kindle|mobile|psp|treo|iris|3g_t|windows ce|opera mobi|windows ce; smartphone;|windows ce; iemobile";
            string WAPPattern = "j2me|nokia109";

            ViewBag.Agent = agent;

            if (System.Text.RegularExpressions.Regex.IsMatch(agent, WAPPattern))
            {
                ViewBag.CSS = "~/Content/WAP.css";
                return View("Detail-WAP");
            }
            else if (System.Text.RegularExpressions.Regex.IsMatch(agent, smartPhonePattern))
            {
                ViewBag.CSS = "~/Content/SmartPhone.css";
                return View("Detail-SmartPhone");
            }
            else
            {
                ViewBag.CSS = "~/Content/Desktop.css";
                return View();
            }
        }

        public ActionResult Search()
        {
            string agent = Request.UserAgent.ToLower();
            string smartPhonePattern = "ipad|ipod|android|opera mini|palm os|palm|hiptop|avantgo|plucker|xiino|blazer|elaine|mini 9.5|vx1000|lge |m800|e860|u940|ux840|compal|wireless| mobi|ahong|lg380|lgku|lgu900|lg210|lg47|lg920|lg840|lg370|sam-r|mg50|s55|g83|t66|vx400|mk99|d615|d763|el370|sl900|mp500|samu3|samu4|vx10|xda_|samu5|samu6|samu7|samu9|a615|b832|m881|s920|n210|s700|c-810|_h797|mob-x|sk16d|848b|mowser|s580|r800|471x|v120|rim8|c500foma:|160x|x160|480x|x640|t503|w839|i250|sprint|w398samr810|m5252|c7100|mt126|x225|s5330|s820|htil-g1|fly v71|s302|-x113|novarra|k610i|-three|8325rc|8352rc|sanyo|vx54|c888|nx250|n120|mtk |c5588|s710|t880|c5005|i;458x|p404i|s210|c5100|teleca|s940|c500|s590|foma|samsu|vx8|vx9|a1000|_mms|myx|a700|gu1100|bc831|e300|ems100|me701|me702m-three|sd588|s800|8325rc|ac831|mw200|brew |d88|htc/|htc_touch|355x|m50|km100|d736|p-9521|telco|sl74|ktouch|m4u/|me702|8325rc|kddi|phone|lg |sonyericsson|samsung|240x|x320|vx10|nokia|sony cmd|motorola|up.browser|up.link|mmp|symbian|smartphone|midp|wap|vodafone|o2|pocket|kindle|mobile|psp|treo|iris|3g_t|windows ce|opera mobi|windows ce; smartphone;|windows ce; iemobile";
            string WAPPattern = "j2me|nokia109";

            ViewBag.Agent = agent;

            if (System.Text.RegularExpressions.Regex.IsMatch(agent, WAPPattern))
            {
                ViewBag.CSS = "~/Content/WAP.css";
                return View("Search-WAP");
            }
            else if (System.Text.RegularExpressions.Regex.IsMatch(agent, smartPhonePattern))
            {
                ViewBag.CSS = "~/Content/SmartPhone.css";
                return View("Search-SmartPhone");
            }
            else
            {
                ViewBag.CSS = "~/Content/Desktop.css";
                return View();
            }
        }
        public ActionResult header()
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.client = client.clientId;
            return PartialView();
        }

        public ActionResult footer()
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.client = client.clientId;
            return PartialView();
        }
    }
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WapFront.Util;

namespace WapFront.Controllers
{
    public class MusicController : Controller
    {
        //
        // GET: /Music/

        public ActionResult Index(int? id)
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.CSSClass = "music";
            ViewBag.Title = "Âm nhạc";
            if (id.HasValue)
            {
                return View("Detail/Index" + client.client);
            }
            else
            {
                return View("Index" + client.client);
            }
            
        }

    }
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WapFront.Util;

namespace WapFront.Controllers
{
    public class PictureController : Controller
    {
        //
        // GET: /Picture/

        public ActionResult Index()
        {
            ClientUtil client = new ClientUtil(Request.UserAgent.ToLower());
            ViewBag.CSS = client.css;
            ViewBag.CSSClass = "image";
            ViewBag.Title = "Ảnh";
            return View("Index" + client.client);
        }

    }
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/Index-SMP.cshtml
@{
    ViewBag.Title = "Index - SMP ";
}
<div class="breadcrumb">
	<ul>
		<li class="end"><a href="index.html" title="TRANG CHỦ">Trang chủ</a></li>
	</ul>
</div> 
<div class="clearfix" style="height:0;"></div>           
<div id="searchbox">
	<div class="keyword"> 
		<span class="hot">Chủ đề HOT</span>:  
		<a href="category.html?keyword=1">Đại học</a> <span style="font-size: 12px;">|</span>	   
		<a href="category.html?keyword=2">Biển đảo</a> <span style="font-size: 12px;">|</span> 
		<a href="category.html?keyword=3c">Điểm sàn khối A</a> <span style="font-size: 12px;">|</span>  
		<a href="category.html?keyword=4">Sức khỏe</a> <span style="font-size: 12px;">|</span> 
		<a href="category.html?keyword=5">Tiêm chủng</a> <span style="font-size: 12px;">|</span>
		<a href="category.html?keyword=5h">Tin nhanh Worldcup</a>     
	</div>
</div>
<div class="clearfix"></div>
<div id="content">
	<h2><span>Game mới nhất</span></h2>
	<div class="v-list">
		<div class="v-item ">
			<table>
				<tr>
					<td class="left">
						<a href="detail.html">
							<img alt="Máy bay sắp cất cánh, hành khách “đòi” quay lại" src="~/Assets/Upload/g2.jpg">
						</a>
					</td>
					<td class="right">
						<div class="title"><a href="detail.html">Dragon quest, game mô phỏng theo bộ truyện ăn khách</a>
						</div>
						<span class="icon-apple-b"></span>
						<span class="icon-and-b"></span>
						<span class="icon-java-b"></span>
						<div class="subtitle"> 
							<span class="ms-seen">
								15  Lượt tải về							
							</span>
							<div class="clearfix"></div>
							<span>
								<a href="detail.html">(tải về/3000d)
								</a>
							</span>
						</div>
					</td>
				</tr>
			</table>
		</div>
		<div class="v-item last">
			<table>
				<tr>
					<td class="left">
						<a href="detail.html">
							<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/g1.jpg">
							
						</a>
					</td>
					<td class="right">
						<div class="title"><a href="detail.html">After earth, sống sót ở trái đất ! </a>
						</div>
						<span class="icon-apple-b"></span>
						<span class="icon-and-b"></span>
						<span class="icon-java-b"></span>
						<div class="subtitle"> 
							<span class="ms-seen">
								0  lượt tải về							
							</span>
							<div class="clearfix"></div>
							<span>
								<a href="detail.html">(tải về/3000d)
								</a>
							</span>
						</div>
					</td>
				</tr>
			</table>	
		</div>
	</div>

	<h2><span>Bài hát mới nhất</span></h2>
	<div class="v-list">
		<div class="v-item " style="padding:0px">
			<table class="table4music" border="0" cellspacing="0" cellpadding="0">
				<thead>
					<tr>
						<td width="45%">Tên bài hát</td>
						<td width="40%">Ca sĩ</td>
						<td>nghe</td>
					</tr>
				</thead>
				<tbody>
					<tr onclick="location.href='#.html'">
						<td class="songname">Indestructable</td>
						<td class="artist">Girls Generation</td>
						<td>2824</td>
					</tr>
					<tr onclick="location.href='#.html'">
						<td class="songname">River flow in you - live in Seoul</td>
						<td class="artist">Yiruma</td>
						<td>1102</td>
					</tr>
					<tr onclick="location.href='#.html'">
						<td class="songname">Đồng xanh</td>
						<td class="artist">Vy Oanh</td>
						<td>0</td>
					</tr>
					<tr onclick="location.href='#.html'">
						<td class="songname">Nắng ấm xa dần</td>
						<td class="artist">Sơn Tùng M-TP</td>
						<td>11212</td>
					</tr>
				</tbody>
			</table>

		</div>
		<div class="clearfix"></div>
		
	</div>
	<div class="clearfix"></div>
	<h2><span>Video mới nhất</span></h2>
	<div class="v-list">
		<div class="v-item ">
			<table>
				<tr>
					<td class="left">
						<a href="detail.html">
							<img alt="Máy bay sắp cất cánh, hành khách “đòi” quay lại" src="~/Assets/Upload/v2.jpg">
						</a>
					</td>
					<td class="right">
						<div class="title"><a href="detail.html">12 cung hoàng đạo sẽ làm gì nếu trong wc... hết giấy ?</a>
						</div>
						
						<div class="subtitle"> 
							<span class="ms-seen">
								15  lượt xem							
							</span>
							<div class="clearfix"></div>
							<span>
								<a href="detail.html">(tải về/3000d)
								</a>
							</span>
						</div>
					</td>
				</tr>
			</table>
		</div>
		<div class="v-item last">
			<table>
				<tr>
					<td class="left">
						<a href="detail.html">
							<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/v1.jpg">
							
						</a>
					</td>
					<td class="right">
						<div class="title"><a href="detail.html">F(x) RedLight - MV </a>
						</div>
						
						<div class="subtitle"> 
							<span class="ms-seen">
								0  lượt xem							
							</span>
							<div class="clearfix"></div>
							<span>
								<a href="detail.html">(tải về/3000d)
								</a>
							</span>
						</div>
					</td>
				</tr>
			</table>	
		</div>
	</div>

	<h2><span>Hình mới nhất</span></h2>
	<div class="v-list table4pic" >
		<div class="v-item ">
			<table>
				<tr>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/11.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/1.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
				</tr>
				<tr>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/10.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/2.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
				</tr>
				<tr>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/8.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/4.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
				</tr>
				<tr>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/5.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
					<td>
						<img alt="Chú mèo Shironeko tiếp tục làm mưa làm gió trên internet " src="~/Assets/Upload/6.jpg">
						<a href="#">Xem/Tải xuống</a>
					</td>
				</tr>
			</table>
		</div>
</div>

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/Index-WAP.cshtml
@{
    ViewBag.Title = "Index - smp ";
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/footer.cshtml
@switch ((int)ViewBag.client)
{
    case 1:
    case 2:
        <footer>
            <div class="clearfix"></div>
            <h2>
                <span>Hướng dẫn</span>
            </h2>
            <a href="index.html" class="referral_service" title="Hướng dẫn">Hướng dẫn</a>
            <a href="index.html" class="referral_service" title="Cách thức thanh toán">Cách thức thanh toán</a>
            <a href="index.html" class="referral_service" title="Điều kiện sử dụng">Điều kiện sử dụng</a>
            <div class="clearfix"></div>
            <div id="footer">
                <div id="footer_left">
                    <a href="~/Images/downloadcontent/avideo.htm" class="home"></a>
                    <a href="#" class="back_top">&nbsp;</a>
                </div>
                <div class="clear"></div>
                <div class="copyright">
                    <p>Lorem lipsum</p>
                    <p>Address: this is address</p>
                    <p>Email: email@mail.com</p>
                </div>
            </div>
        </footer>
        break;
    default:
        <footer>
            <p>Lorem lipsum</p>
            <p>Address: this is address</p>
            <p>Email: email@mail.com</p>
        </footer>
        break;
}

05_IMPLEMENTATION/05_02_Metbox_Site‏/trunk/WapFront/Views/Home/header.cshtml
@switch ((int)ViewBag.client)
{
    case 1:
        <header>
            <div id="header">
                <div class="left"><a href="#"></a></div>
                <div class="right">
                    <a class="search" href="search.html" title="Tìm kiếm"><span></span></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="bottom">
                <div class="clearfix"></div>
            </div>
            <div id="userbar">
                Không nhận diện được thuê bao <a href="login.html">Đăng nhập</a>
            </div>
            <div id="mainmenu">
                <table cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr style="margin: 0;">
                            
                            <td>@Html.ActionLink("Trò chơi", "Index", "Game")</td>
                            <td>@Html.ActionLink("Nhạc", "Index", "Music")</td>
                            <td>@Html.ActionLink("Video", "Index", "Video")</td>
                            <td>@Html.ActionLink("Hình ảnh", "Index", "Picture")</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </header>
              break;
    case 2:
        <header>
            <div id="header">
                <div class="left"><a href="#"></a></div>
                <div class="right">
                    <a class="search" href="search.html" title="Tìm kiếm"><span></span></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="bottom">
                <div class="clearfix"></div>
            </div>
            <div id="userbar">
                Không nhận diện được thuê bao <a href="login.html">Đăng nhập</a>
            </div>
            <div id="mainmenu">
                <table cellpadding="0" cellspacing="0" style="table-layout:fixed; width:100%; text-align:center; text-transform: uppercase">
                    <tbody>
                        <tr style="margin: 0;">
                            <td>@Html.ActionLink("Trò chơi", "Index", "Game")</td>
                            <td>@Html.ActionLink("Nhạc", "Index", "Music")</td>
                            <td>@Html.ActionLink("Video", "Index", "Video")</td>
                            <td>@Html.ActionLink("Hình ảnh", "Index", "Picture")</td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </header>
        break;
    default:
        <header>
            <div class="menu">
                <span><span class="icon-home"></span>@Html.ActionLink("Home", "Index", "Home")</span>
                <span><span class="icon-game"></span>@Html.ActionLink("Trò chơi", "Index", "Game")</span>
                <span><span class="icon-game"></span>@Html.ActionLink("Nhạc", "Index", "Music")</span>
                <span><span class="icon-game"></span>@Html.ActionLink("Video", "Index", "Video")</span>
                <span><span class="icon-game"></span>@Html.ActionLink("Hình ảnh", "Index", "Picture")</span>      
                <span><span class="icon-pay"></span><a href="#">Nạp tiền</a></span>
                <span><span class="icon-help"></span><a href="#">Hướng dẫn</a></span>
                <span><span class="icon-faq"></span><a href="#">Điều khoản sử dụng</a></span>
            </div>
            <div class="banner"></div>
        </header>
        break;
}