05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Controllers/GameCategoryController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using log4net;
using WAP_CMS.Models;
using System.Web.Script.Serialization;

namespace WAP_CMS.Controllers
{
    public class GameCategoryController : Controller
    {
        private CMSDbContext db = new CMSDbContext();

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);


        [AccountAuthorization]
        public ActionResult Index()
        {
            try
            {
                //var categories = db.TBL_Game_Categorys.Where(c => c.status != 9).OrderBy(c => c.category_name);
                using (db)
                {
                    var categories = from cat in db.TBL_Game_Categorys
                                     where cat.status != 9
                                     select new
                                     {
                                         cat,
                                         total = (from r in db.TBL_Category_Games where r.game_category_row_id == cat.row_id select r).Count()
                                     }; 

                    List<TBL_Game_Category> lst = new List<TBL_Game_Category>();

                    foreach (var category in categories)
                    {
                        category.cat.totalGames = category.total;

                        lst.Add(category.cat);
                    }

                    return View("Index", lst);
                }

            }
            catch (Exception exception)
            {
                log.Error("Game/Category", exception);
                return View("Error");
            }
        }


        [AccountAuthorization]
        public ActionResult Create()
        {
            return View();
        }


        [AccountAuthorization]
        [HttpPost]
        public ActionResult Create(TBL_Game_Category category)
        {            
            try
            {
                TBL_Account registerPerson = ((TBL_Account)Session["_ADMIN__"]);

                category.register_person = registerPerson.row_id;
                category.update_person = registerPerson.row_id;
                category.register_datetime = DateTime.Now;
                category.update_datetime = DateTime.Now;

                if (ModelState.IsValid)
                {
                    int checkGame = db.TBL_Game_Categorys.Where(c => c.category_name.Equals(category.category_name)).Count();

                    if (checkGame > 0)
                    {
                        ModelState.AddModelError("category_name", "Category name is already exists! Please choose another");

                        return View(category);
                    }
                    else
                    {
                        db.TBL_Game_Categorys.Add(category);
                        db.SaveChanges();

                        TempData["MESSAGE"] = "Category is created successfully";
                        return RedirectToAction("Edit", new { id = category.row_id});
                    }
                }

                return View(category);
            }
            catch (Exception exception)
            {
                log.Error("Game Category/Create", exception);
                return View("Error");
            }

        }


        [AccountAuthorization]
        public ActionResult Edit(int id = 0)
        {
            try
            {
                ViewBag.languages = new SelectList(db.TBL_Languages.ToList(), "row_id", "language_name");

                TBL_Game_Category category = db.TBL_Game_Categorys.Find(id);

                if (category != null)
                {
                    using (db)
                    {
                        var gameCategoriesTran = from cat in db.TBL_Tran_Game_Categorys
                                                 join lang in db.TBL_Languages
                                                 on cat.language_id equals lang.row_id
                                                 where cat.category_row_id == category.row_id
                                                 select new
                                                 {
                                                     cat
                                                     , lang.language_name
                                                     
                                                 };

                        List<TBL_Tran_Game_Category> gameCats = new List<TBL_Tran_Game_Category>();

                        foreach (var gameCat in gameCategoriesTran)
                        {
                            gameCat.cat.language_name = gameCat.language_name;

                            gameCats.Add(gameCat.cat);
                        }


                        ViewBag.TranGameCategories = gameCats;
                    }

                    return View(category);
                }
                else
                    return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                log.Error("Game Category/Edit/id", exception);
                return View("Error");
            }
        }


        [AccountAuthorization]
        [HttpPost]
        public ActionResult Edit(TBL_Game_Category category)
        {
            try
            {
                using (db)
                {
                    ViewBag.languages = new SelectList(db.TBL_Languages.ToList(), "row_id", "language_name");

                    var gameCategoriesTran = from cat in db.TBL_Tran_Game_Categorys
                                             join lang in db.TBL_Languages
                                             on cat.language_id equals lang.row_id
                                             where cat.category_row_id == category.row_id
                                             select new
                                             {
                                                 cat
                                                 ,
                                                 lang.language_name

                                             };

                    List<TBL_Tran_Game_Category> gameCats = new List<TBL_Tran_Game_Category>();

                    foreach (var gameCat in gameCategoriesTran)
                    {
                        gameCat.cat.language_name = gameCat.language_name;

                        gameCats.Add(gameCat.cat);
                    }


                    ViewBag.TranGameCategories = gameCats;
                

                    TBL_Account registerPerson = ((TBL_Account)Session["_ADMIN__"]);

                    category.update_person = registerPerson.row_id;
                    category.update_datetime = DateTime.Now;

                    if (ModelState.IsValid)
                    {
                        int checkGame = db.TBL_Game_Categorys.Where(c => c.category_name.Equals(category.category_name) && c.row_id != category.row_id).Count();

                        if (checkGame > 0)
                        {
                            ModelState.AddModelError("category_name", "Category name is already exists! Please choose another");

                            return View(category);
                        }
                        else
                        {
                            db.Entry(category).State = EntityState.Modified;
                            db.SaveChanges();

                            TempData["MESSAGE"] = "Category is saved successfully";
                            return View(category);
                        }
                    }
                }

                return View(category);
            }
            catch (Exception exception)
            {
                log.Error("Game Category/Edit", exception);
                return View("Error");
            }
        }


        [AccountAuthorization]
        [HttpGet]
        public ActionResult TranGameCategory(int catid, int lang = 0)
        {
            try
            {
                if (catid > 0 && lang > 0)
                {
                    TBL_Tran_Game_Category tranGameCategory = db.TBL_Tran_Game_Categorys.Where(g => g.language_id == lang && g.category_row_id == catid).SingleOrDefault();

                    if (tranGameCategory != null)
                    {
                        return PartialView("TranGameCategory", tranGameCategory);
                    }
                }
            }
            catch (Exception exception)
            {
                log.Error("Tran Game Category", exception);
                return View("Error");
            }
            return PartialView();
        }


        [AccountAuthorization]
        [HttpPost]
        public ActionResult TranGameCategory(TBL_Tran_Game_Category tranGameCategory)
        {
            try
            {
                TBL_Account registerPerson = ((TBL_Account)Session["_ADMIN__"]);


                tranGameCategory.update_person = registerPerson.row_id;

                tranGameCategory.update_datetime = DateTime.Now;

                if (tranGameCategory.row_id == 0)
                {
                    tranGameCategory.register_person = registerPerson.row_id;
                    tranGameCategory.register_datetime = DateTime.Now;
                }

                //if (ModelState.IsValid)
                //{

                    TBL_Tran_Game_Category existsTran = db.TBL_Tran_Game_Categorys.Where(t => t.language_id == tranGameCategory.language_id && t.category_row_id == tranGameCategory.category_row_id).SingleOrDefault();

                    if (existsTran != null)
                    {
                        existsTran.update_person = tranGameCategory.update_person;

05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Views/GameCategory/Create.cshtml
@model WAP_CMS.Models.TBL_Game_Category
@{
    ViewBag.Title = "Create Game Category";
    
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

<div id="content">
    <div class="inner_content">
        <div class="statistic clearfix">
            <div class="current_page float_left">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>

        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span6">
                    <div class="well grey">
                        <div class="well-header">
                            <h5>Game </h5>
                        </div>

                        <div class="well-content no-search">
                            @using (Html.BeginForm())
                            {
                                @Html.ValidationSummary(true)

                                <div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.category_name)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.TextBoxFor(model => model.category_name, new { @class = "span5" })
                                    </div>

                                    @Html.ValidationMessageFor(model => model.category_name)
                                </div>
                                
                                <div class="form_row">
                                    <label class="field_name custom-field_name-for-large-area">
                                        @Html.LabelFor(model => model.Enable)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.CheckBoxFor(model => model.Enable)
                                    </div>
                                </div>
                                
                                
                                <div class="form_row">
                                    <div class="field action-field">
                                        <input type="submit" value="Create" class="blue btn custom-input-btn" />
                                        <a href="@Url.Action("Index", "GameCategory")" class="red btn custom-a-btn">Cancel</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Views/GameCategory/Edit.cshtml
@model WAP_CMS.Models.TBL_Game_Category
@{
    ViewBag.Title = "Edit Game Category";
    
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

<div id="content">
    <div class="inner_content">
        <div class="statistic clearfix">
            <div class="current_page float_left">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>

        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span6">
                    <div class="well grey">
                        <div class="well-header">
                            <h5>
                                @if (TempData["MESSAGE"] != null && TempData["MESSAGE"].ToString().Length > 0)
                                {
                                    <font style="color: red; font-weight: bold;">@TempData["MESSAGE"]</font>
                                }
                            </h5>
                        </div>

                        <div class="well-content no-search">
                            @using (Html.BeginForm())
                            {
                                
                                    
                                @Html.ValidationSummary(true)

                                @Html.HiddenFor(model => model.row_id)
                                @Html.HiddenFor(model => model.register_person)
                                @Html.HiddenFor(model => model.register_datetime)
                                
                                <div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.category_name)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.TextBoxFor(model => model.category_name, new { @class = "span5" })
                                    </div>

                                    @Html.ValidationMessageFor(model => model.category_name)
                                </div>
                                
                                <div class="form_row">
                                    <label class="field_name custom-field_name-for-large-area">
                                        @Html.LabelFor(model => model.Enable)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.CheckBoxFor(model => model.Enable)
                                    </div>
                                </div>
                                
                                
                                <div class="form_row">
                                    <div class="field action-field">
                                        <input type="submit" value="Update" class="blue btn custom-input-btn" />
                                        <a href="@Url.Action("Index", "GameCategory")" class="red btn custom-a-btn">Cancel</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    
        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span6">
                    <div class="well grey">
                        <div class="well-header">
                            <h5>Translation</h5>

                            <div class="float_right" style="margin-top: 10px; margin-right: 5px">
                                <a href="#" onclick="ShowTranslationDialog(@Model.row_id,0)" class="blue btn btn-small">
                                    <i class="icon-plus-sign custom-icon-plus-sign"></i>
                                    Add Translation
                                </a>
                            </div>
                        </div>

                        <div class="well-content no-search">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                            
                                        <td>Language</td>
                                        <td>Category Name</td>
                                        <td>Active</td>
                                        <td class="last-column">&nbsp;</td>
                                        <td class="last-column">&nbsp;</td>
                                    </tr>
                                </thead>

                                <tbody id="tblGameCategory">
                                    @foreach (var item in ViewBag.TranGameCategories)
                                    {
                                        <tr>
                                            <td>@item.language_name</td>
                                            <td width="26%">@item.category_name</td>
                                            
                                            <td class="action-column">
                                                @if(item.status == 1)
                                                {
                                                    @:Yes    
                                                }
                                                else
                                                {
                                                    @:No
                                                }
                                            </td>

                                            <td class="action-column">
                                                <a href="#" onclick="ShowTranslationDialog(@Model.row_id, @item.language_id)" class="grey btn action-btn">
                                                    <i class="icon-edit"></i> Edit
                                                </a>
                                            </td>

                                            <td class="action-column">
                                                <a href="#" onclick="ShowDeleteTranslationDialog(@item.language_id)"  role="button" class="btn red delete-btn action-btn" data-toggle="modal">
                                                    <i class="icon-remove-sign"></i> Delete
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="DeleteTranslationDlg" class="modal hide fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
        <div class="modal-body">
            <p>Are you sure want to delete this translation ?</p>

            <input type="hidden" id="delTranGameCategoryLanguage" />
        </div>

        <div class="modal-footer">
            <a href="#" data-dismiss="modal" aria-hidden="true" class="btn grey">NO</a>
            <input type="button" class="btn red" value="Yes" onclick="DeleteTranslation()" />
        </div>
</div>


<div id="TranSlationDlg" class="modal hide fade" tabindex="-1" data-width="760">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
        <h3>Translation</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            @using (Html.BeginForm("TranGameCategory", "GameCategory"))
            {
                <div class="span12" id="TranSlationFormContainer">
                    <div class="form_row">
                        <label class="field_name custom-field_name-for-large-area">
                            Language
                        </label>
                        <div class="field">
                            @Html.DropDownList("language_row_id", (SelectList)ViewBag.languages)
                        </div>
                    </div>

                     
                </div>
            }
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" data-dismiss="modal" aria-hidden="true" class="btn grey">Close</a>
        <a href="#" onclick="SaveTranslation()" class="btn red">Save changes</a>
    </div>
</div>

<script type="text/javascript">
    function ShowTranslationDialog(id, langId) {
        jQuery.ajax({
            // Call EditPartialView action method
            url: "/GameCategory/TranGameCategory",
            data: { catid: id, lang: langId },
            type: 'Get',
            success: function (msg) {
                if (langId > 0) {
                    jQuery('#language_row_id').val(langId);
                }
                jQuery('.tran_category_name').remove();

                jQuery('#TranSlationFormContainer').append(msg);

                jQuery('#TranSlationDlg').modal('show');
            },
            error: function () {
                alert("Error occurs! Please try again or contact support for more information");
            }
        });
    }

    function SaveTranslation() {
        if (jQuery.trim(jQuery('#tran_game_category_name').val()).length > 0) {
            jQuery.post('/GameCategory/TranGameCategory'
                    , {
                        "row_id": jQuery('#tran_game_category_row_id').val()
                        , "register_person": jQuery('#tran_game_category_register_person').val()
                        , "register_datetime": jQuery('#tran_game_category_register_datetime').val()
                        , "category_name": jQuery('#tran_game_category_name').val()
                        , "Enable": jQuery('#tran_game_category_enable').is(':checked')
                        , "language_id": jQuery('#language_row_id').val()
                        , "category_row_id": "@Model.row_id"
                    }
                   , function (data) {
                       var tblGameCategory = jQuery("#tblGameCategory");
                       tblGameCategory.html('');
                       for (var i = 0; i < data.length; i++) {
                           var item = data[i];

                           var t = '<tr><td>' + item.language_name + '</td><td width="26%">' + item.category_name + '</td><td>' + ((item.status == 1) ? 'Yes' : 'No') + '</td>'

                                + '<td class="action-column"><a href="#" onclick="ShowTranslationDialog(@Model.row_id,' + item.language_id + ')" class="grey btn action-btn"><i class="icon-edit"></i> Edit</a></td>'

                                + '<td class="action-column"><a href="#" onclick="ShowDeleteTranslationDialog(' + item.language_id + ')" role="button" class="btn red delete-btn action-btn" data-toggle="modal"><i class="icon-remove-sign"></i> Delete</a></td></tr>';

                           tblGameCategory.append(t);
                       }

                       jQuery('#TranSlationDlg').modal('hide');
                   }
                   , "json");
        }
        else {
            jQuery('#tranGameCategoryErrorMessage').show();

            jQuery('#tran_game_category_name').keyup(function () { jQuery('#tranGameCategoryErrorMessage').hide(); });
        }
    }

    function ShowDeleteTranslationDialog(langId) {
        jQuery("#delTranGameCategoryLanguage").val(langId);

        jQuery('#DeleteTranslationDlg').modal('show');
    }

    function DeleteTranslation() {

        jQuery.post('/GameCategory/DeleteTranGameCategory'
                    , {
                        "catid": "@Model.row_id"
                        , "langId": jQuery('#delTranGameCategoryLanguage').val()
                    }
                   , function (data) {
                       var tblGameCategory = jQuery("#tblGameCategory");
                       tblGameCategory.html('');
                       for (var i = 0; i < data.length; i++) {
                           var item = data[i];

                           var t = '<tr><td>' + item.language_name + '</td><td width="26%">' + item.category_name + '</td><td>' + ((item.status == 1) ? 'Yes' : 'No') + '</td>'

                                + '<td class="action-column"><a href="#" onclick="ShowTranslationDialog(@Model.row_id,' + item.language_id + ')" class="grey btn action-btn"><i class="icon-edit"></i> Edit</a></td>'

                                + '<td class="action-column"><a href="#" onclick="ShowDeleteTranslationDialog(' + item.language_id + ')" role="button" class="btn red delete-btn action-btn" data-toggle="modal"><i class="icon-remove-sign"></i> Delete</a></td></tr>';

                           tblGameCategory.append(t);
                       }

                       jQuery('#DeleteTranslationDlg').modal('hide');
                   }
                   , "json");
        
    }
</script>

05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Views/GameCategory/Index.cshtml
@model IEnumerable<WAP_CMS.Models.TBL_Game_Category>
@{
    ViewBag.Title = "Game Category";
    var i = 1;
}

<div id="content">
    <div class="inner_content">
        <div class="statistic clearfix">
            <div class="float_right">
                <a href="@Url.Action("Create", "GameCategory")" class="blue btn btn-xlarge">
                    <i class="icon-plus-sign custom-icon-plus-sign"></i>
                    New @ViewBag.Title
                </a>
            </div>
        </div>

        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span12">
                    <div class="well blue">
                        <div class="well-header">
                            <h5>All record (total: @Model.Count())</h5>
                        </div>

                        <div class="well-content">
                            <div class="responsive_table_scroll">
                                <table class="table table-striped table-bordered table-hover datatable" width="100%">
                                    <thead>
                                        <tr>
                                            <td>#</td>
                                            <td>@Html.DisplayNameFor(model => model.category_name)</td>
                                            <td>@Html.DisplayNameFor(model => model.totalGames)</td>
                                            <td>@Html.DisplayNameFor(model => model.Enable)</td>
                                            <td>Action</td>
                                            <td class="last-column">&nbsp;</td>
                                            <td class="last-column">&nbsp;</td>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td class="no-column">@(i++)</td>
                                                <td width="26%">@Html.DisplayFor(modelItem => item.category_name)</td>
                                                <td width="12%">@Html.DisplayFor(modelItem => item.totalGames)</td>
                                                <td width="12%">@Html.DisplayFor(modelItem => item.Enable)</td>
                                                <td class="action-column">
                                                    <a href="@Url.Action("Detail", "GameCategory", new { id = item.row_id })" class="light_blue btn action-btn">
                                                        <i class="icon-reorder"></i> Details
                                                    </a>
                                                </td>

                                                <td class="action-column">
                                                    <a href="@Url.Action("Edit", "GameCategory", new { id = item.row_id })" class="grey btn action-btn">
                                                        <i class="icon-edit"></i> Edit
                                                    </a>
                                                </td>

                                                <td class="action-column">
                                                    <a href="#" onclick="ShowDeleteCategoryDlg(@item.row_id)" role="button" class="btn red delete-btn action-btn" data-toggle="modal" alt="@item.row_id">
                                                        <i class="icon-remove-sign"></i> Delete
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="DeleteCategoryDlg" class="modal hide fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
    @using (Html.BeginForm("Delete", "GameCategory"))
    {
        <div class="modal-body">
            <p>Are you sure want to delete this category ?</p>

            <input type="hidden" name="id" id="id" />
        </div>

        <div class="modal-footer">
            <a href="#" data-dismiss="modal" aria-hidden="true" class="btn grey">NO</a>
            <input type="submit" class="btn red" value="Yes" />
        </div>
    }
</div>

<script type="text/javascript">
    function ShowDeleteCategoryDlg(id) {        
        jQuery("#id").val(id);

        jQuery('#DeleteCategoryDlg').modal('show');
    }
</script>