05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;

using log4net;
using WAP_CMS.Models;
using WAP_CMS.Common;

namespace WAP_CMS.Controllers
{
    public class VideoController : Controller
    {
        private CMSDbContext db = new CMSDbContext();

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private Dictionary<string, HttpPostedFileBase> postedFileList = new Dictionary<string, HttpPostedFileBase>();

        [AccountAuthorization]
        public ActionResult Index(int catId = -1)
        {
            try
            {
                var categories = db.TBL_Video_Categorys.Where(c => c.status != 9);
                ViewBag.categories = categories.ToList();
                ViewBag.catId = catId;
                ViewBag.VideoCategory = new SelectList(categories.ToList(), "row_id", "category_name");
                List<TBL_Video> vList = new List<TBL_Video>();
                if(catId == -1){
                    vList = db.TBL_Videos.Where(g => g.status != 9).OrderByDescending(g => g.update_datetime).ToList();
                }else{
                    var videosWithCatFilter = from v in db.TBL_Videos
                                              join c in db.TBL_Category_Videos
                                              on v.row_id equals c.video_row_id
                                              where v.status != 9 && c.video_category_row_id == catId
                                              orderby v.update_datetime descending
                                              select new
                                              {
                                                  v
                                              };
                    foreach (var vid in videosWithCatFilter)
                    {
                        vList.Add(vid.v);
                    }
                }
                
                
                var videosList = new List<TBL_Video>();
                using (db)
                {
                    foreach (var video in vList)
                    {
                        video.categories = new List<TBL_Video_Category>();
                        var videoCategorys = from c in db.TBL_Video_Categorys
                                             join l in db.TBL_Category_Videos
                                             on c.row_id equals l.video_category_row_id
                                             where l.video_row_id == video.row_id && c.status != 9
                                             select new
                                             {
                                                 c
                                             };

                        foreach (var category in videoCategorys)
                        {
                            video.categories.Add(category.c);
                        }
                        videosList.Add(video);
                    }
                }
                
                return View("Index", videosList);
            }
            catch (Exception exception)
            {
                log.Error("Video/Index", exception);
                return View("Error");
            }
        }

        [AccountAuthorization]
        public ActionResult Create()
        {
            return View();
        }

        [AccountAuthorization]
        [HttpPost]
        public ActionResult Create(TBL_Video video)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    bool isError = false;
                    HttpFileCollectionBase postedFiles = Request.Files;

                    for (int i = 0; i < postedFiles.Count; i++)
                    {
                        HttpPostedFileBase file = postedFiles[i];
                        string fileName = file.FileName.ToLower();


                        switch (postedFiles.GetKey(i))
                        {
                            case "Image":
                                if (fileName.Length > 0)
                                {
                                    if (file.ContentType.Contains("image"))
                                    {
                                        postedFileList.Add("Image", file);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError("ImageURL", "The Image field must be image.");
                                        isError = true;
                                    }
                                }
                                else
                                {
                                    postedFileList.Remove("Image");
                                }

                                break;
                            case "videourl":
                                if (fileName.Length > 0)
                                {
                                    if (file.ContentType.Contains("3gpp"))
                                    {
                                        postedFileList.Add("videourl", file);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError("videourl", "The Video field must be 3GP file.");
                                        isError = true;
                                    }
                                }
                                else
                                {
                                    postedFileList.Remove("videourl");
                                }

                                break;
                            default:
                                break;
                        }
                    }

                    // File upload error
                    if (isError)
                    {
                        return View(video);
                    }
                    else
                    {
                        foreach (var item in postedFileList)
                        {
                            HttpPostedFileBase file = item.Value;

                            switch (item.Key)
                            {
                                case "Image":
                                    video.img = Util.FtpUploadVideoImg((new WebImage(file.InputStream)).Resize(Convert.ToInt32(ConfigurationManager.AppSettings["ImageWidth"]), Convert.ToInt32(ConfigurationManager.AppSettings["ImageHeight"]), true, true));

                                    break;
                                case "videourl":
                                    video.videosize = file.ContentLength;
                                    video.videourl = Util.FtpUploadVideo(file);

                                    break;


                            }
                        }

                        TBL_Account registerPerson = ((TBL_Account)Session["_ADMIN__"]);

                        video.register_person = registerPerson.row_id;
                        video.update_person = registerPerson.row_id;

                        video.register_datetime = DateTime.Now;
                        video.update_datetime = DateTime.Now;

                        db.TBL_Videos.Add(video);
                        db.SaveChanges();

                        TempData["MESSAGE"] = "Your video is created successfully";
                        return RedirectToAction("Edit", new { id = video.row_id });
                    }


                }
                catch (Exception exception)
                {
                    log.Error("Video/Create", exception);
                    return View("Error");
                }
            }

            return View(video);
        }

        [AccountAuthorization]
        public ActionResult Edit(int id = 0)
        {
            try
            {
                TBL_Video video = db.TBL_Videos.Find(id);

                if (video != null)
                {
                    ViewBag.languages = new SelectList(db.TBL_Languages.ToList(), "row_id", "language_name");

                    using (db)
                    {
                        var videoTrans = from g in db.TBL_Tran_Videos
                                         join lang in db.TBL_Languages
                                         on g.language_id equals lang.row_id
                                         where g.video_row_id == video.row_id
                                         select new
                                         {
                                             g
                                             ,
                                             lang.language_name

                                         };

                        List<TBL_Tran_Video> videos = new List<TBL_Tran_Video>();

                        foreach (var videoTran in videoTrans)
                        {
                            videoTran.g.language_name = videoTran.language_name;

                            videos.Add(videoTran.g);
                        }


                        ViewBag.TranVideos = videos;


                        video.allCategories = db.TBL_Video_Categorys.Where(c => c.status != 9).ToList();

                        var videoCategorys = from c in db.TBL_Video_Categorys
                                             join l in db.TBL_Category_Videos
                                             on c.row_id equals l.video_category_row_id
                                             where l.video_row_id == video.row_id && c.status != 9
                                             select new

05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Views/Video/Create.cshtml
@model WAP_CMS.Models.TBL_Video

@{
    ViewBag.Title = "Create Video";
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

<div id="content">
    <div class="inner_content">
        <div class="statistic clearfix">
            <div class="current_page float_left">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>

        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span6">
                    <div class="well grey">
                        <div class="well-header">
                            <h5>Video Information</h5>
                        </div>

                        <div class="well-content no-search">
                            @using (Html.BeginForm("Create", "Video", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.ValidationSummary(true)

                                <div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.name)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.TextBoxFor(model => model.name, new { @class = "span5" })
                                    </div>

                                    @Html.ValidationMessageFor(model => model.name)
                                </div>

                                <div class="form_row">
                                    <label class="field_name custom-field_name-for-large-area">
                                        @Html.LabelFor(model => model.Enable)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.CheckBoxFor(model => model.Enable)
                                    </div>
                                </div>

                                @*<div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.producer)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.TextBoxFor(model => model.producer, new { @class = "span5" })
                                    </div>
                                </div>*@

                                <div class="form_row">
                                    <label class="field_name custom-field_name-for-large-area">
                                        @Html.LabelFor(model => model.short_description)
                                    </label>

                                    <div class="field custom-field">
                                        @Html.TextAreaFor(model => model.short_description, new { style = "width: 100%; height: 100px" })
                                    </div>

                                    <div class="field custom-field">
                                        @Html.ValidationMessageFor(model => model.short_description)
                                    </div>
                                </div>

                                <div class="form_row">
                                    <label class="field_name custom-field_name-for-large-area">
                                        @Html.LabelFor(model => model.description)
                                    </label>

                                    <div class="field custom-field">
                                        <div class="well-content no-search">
                                            @Html.TextAreaFor(model => model.description, new { style = "width: 100%; height: 300px", @class = "textarea", placeholder = "Enter text..." })
                                        </div>
                                    </div>

                                    <div class="field custom-field">
                                        @Html.ValidationMessageFor(model => model.description)
                                    </div>
                                </div>

                                <div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.img)
                                    </label>

                                    <div class="field custom-field">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="input-append">
                                                <div class="uneditable-input span3">
                                                    <i class="icon-file fileupload-exists"></i>
                                                    <span class="fileupload-name fileupload-preview">
                                                        @Html.DisplayTextFor(model => model.img)
                                                    </span>
                                                </div>

                                                <span class="btn btn-file">
                                                    <span class="fileupload-new">Select file</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <input type="file" name="Image" />
                                                </span>

                                                <a href="#" class="btn fileupload-exists red" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>

                                    @Html.ValidationMessageFor(model => model.img)
                                </div>

                                <div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.videourl)
                                    </label>

                                    <div class="field custom-field">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="input-append">
                                                <div class="uneditable-input span3">
                                                    <i class="icon-file fileupload-exists"></i>
                                                    <span class="fileupload-name fileupload-preview">
                                                        @Html.DisplayTextFor(model => model.videourl)
                                                    </span>
                                                </div>

                                                <span class="btn btn-file">
                                                    <span class="fileupload-new">Select file</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <input type="file" name="videourl" />
                                                </span>

                                                <a href="#" class="btn fileupload-exists red" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>

                                    @Html.ValidationMessageFor(model => model.videourl)
                                </div>

                                @*<div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.iosappurl)
                                    </label>

                                    <div class="field custom-field">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="input-append">
                                                <div class="uneditable-input span3">
                                                    <i class="icon-file fileupload-exists"></i>
                                                    <span class="fileupload-name fileupload-preview">
                                                        @Html.DisplayTextFor(model => model.iosappurl)
                                                    </span>
                                                </div>

                                                <span class="btn btn-file">
                                                    <span class="fileupload-new">Select file</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <input type="file" name="iOSApp" />
                                                </span>

                                                <a href="#" class="btn fileupload-exists red" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>

                                    @Html.ValidationMessageFor(model => model.iosappurl)
                                </div>*@

                                @*<div class="form_row">
                                    <label class="field_name custom-field_name">
                                        @Html.LabelFor(model => model.javaappurl)
                                    </label>

                                    <div class="field custom-field">
                                        <div class="fileupload fileupload-new" data-provides="fileupload">
                                            <div class="input-append">
                                                <div class="uneditable-input span3">
                                                    <i class="icon-file fileupload-exists"></i>
                                                    <span class="fileupload-name fileupload-preview">
                                                        @Html.DisplayTextFor(model => model.javaappurl)
                                                    </span>
                                                </div>

                                                <span class="btn btn-file">
                                                    <span class="fileupload-new">Select file</span>
                                                    <span class="fileupload-exists">Change</span>
                                                    <input type="file" name="JavaApp" />
                                                </span>

                                                <a href="#" class="btn fileupload-exists red" data-dismiss="fileupload">Remove</a>
                                            </div>
                                        </div>
                                    </div>

                                    @Html.ValidationMessageFor(model => model.javaappurl)
                                </div>*@

                                <div class="form_row">
                                    <div class="field action-field">
                                        <input type="submit" value="Create" class="blue btn custom-input-btn" />
                                        <a href="@Url.Action("Index", "Video")" class="red btn custom-a-btn">Cancel</a>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

05_IMPLEMENTATION/05_01_WAP_CMS/Trunk/WAP CMS/Views/Video/Details.cshtml
@model WAP_CMS.Models.Video

@{
    ViewBag.Title = "Video details";
}

<div id="content">
    <div class="inner_content">
        <div class="statistic clearfix">
            <div class="current_page float_left">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>

        <div class="widgets_area">
            <div class="row-fluid">
                <div class="span6">
                    <div class="well blue">
                        <div class="well-header">
                            <h5>Details</h5>
                        </div>

                        <div class="well-content no-search">
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.CreatedAt)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.CreatedAt)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.LastModified)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.LastModified)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.Name)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.Name)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.ShortDescription)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.ShortDescription)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.LongDescription)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.LongDescription)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.Studio)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.Studio)
                                </div>
                            </div>

                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.Duration)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.Duration)
                                </div>
                            </div>
                              
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.Year)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.Year)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.View)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.View)
                                </div>
                            </div>
                                
                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.Download)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.Download)
                                </div>
                            </div>

                            <div class="form_row">
                                <label class="field_name custom-field_name-for-large-area detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.ImageURL)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.ImageURL)

                                    <div style="margin-top:5px;">
                                        <img src="@ViewBag.MediaSourcePath@Html.DisplayFor(model => model.ImageURL)" style="height:100px;" alt="@Html.DisplayFor(model => model.ImageURL)" />
                                    </div>
                                </div>
                            </div>

                            <div class="form_row">
                                <label class="field_name custom-field_name detail-custom-field-name">
                                    @Html.DisplayNameFor(model => model.SourceURL)
                                </label>
                                    
                                <div class="field custom-field">
                                    @Html.DisplayFor(model => model.SourceURL)
                                    @if (@Model.SourceURL != null) {
                                        @Html.DisplayFor(model => model.SizeString)
                                    }
                                </div>
                            </div>

                            <div class="form_row">
                                <div class="field action-field">
                                    <a href="@Url.Action("Edit", "Video", new { id = @Model.Id })" class="grey btn custom-a-btn">Edit</a>
                                    <a href="@Url.Action("Index", "Video")" class="red btn custom-a-btn">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>